# Generated by Django 5.1.6 on 2025-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialState', '0002_rename_answers_answer_rename_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tip_question',
            field=models.BigIntegerField(default=0, max_length=2),
        ),
    ]
