# Generated by Django 5.1.6 on 2025-03-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialState', '0003_question_tip_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='step',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='tip_question',
            field=models.BigIntegerField(default=0),
        ),
    ]
