# Generated by Django 5.1.6 on 2025-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_question_step_alter_question_tip_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tip_question',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
