# Generated by Django 5.1.6 on 2025-03-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('position', models.CharField(default='Noob', max_length=50)),
                ('available', models.BooleanField(default=False)),
                ('last_time_online', models.DateTimeField(auto_now=True, null=True)),
                ('my_buddy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.employee')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.language')),
            ],
            options={
                'unique_together': {('employee', 'language')},
            },
        ),
    ]
