# Generated by Django 5.1.6 on 2025-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_employee_last_time_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='user1234', max_length=25),
        ),
    ]
